[mypy]
python_version = 3.11
warn_unused_ignores = True
no_implicit_optional = True
check_untyped_defs = True
ignore_missing_imports = True
disable_error_code = untyped-decorator, no-untyped-call

[mypy-celery.*]
ignore_missing_imports = True

[mypy-minio.*]
ignore_missing_imports = True

[mypy-yt_dlp.*]
ignore_missing_imports = True
